### ISSUE TITLE
Question on ECS' events

### ISSUE THREAD

**Issue by Darelbi** [sebas77/Svelto-ECS#1]
Ciao Sebastiano:)

I've been following Svelto(both IOC and now ECS too) for a while and I found it really interesting and I hope to see soon the next version.

I really like your decision to put events inside components. As long as events are setup in a deterministic way from Engines there's no problem in having events in components, in your ECS example there's a 1to1 relationship between caller and callback (enemy in range triggered by Unity physics, and 1 engine is listening the event).

 However, how much freedom do we have in using events that way?  How do you see using multiple triggerers and multiple subscribers for the same event?

Let's consider following cases:

** Case 1 (1to1)**

 `IEnemyTrigger` setup an event, `PhysicsEngine` trigger it (assume I implemented a custom physics engine in c#)

There's 1 to 1 caller/callee corrispondence => could we use instead 2 different interfaces? One is used with an Action setter and the other one is used to call the Action, both interfaces are used each 1 by one engine for the same Entity:

    public interface IEnemyTrigger{
        System.Action<GameObject, bool> entityInRange{set;}
    }
    public interface IPhysTrigger{
        void triggerEntityInRange( GameObject go, bool inRange);
    }
    
    public class EnemyTrigger : IEnemyTrigger, IPhysRangeTrigger{
        private PhysAction _entityInRange;
        public PhysAction  IEnemyTrigger.entityInRange { set{ _entityInRange += value;}}
        public void IPhysTrigger.TriggerEntityInRange( GameObject go, bool inRange){
             _entityInRange( go, inRange);
        }
    }

** Case 2 (X to Y)**

However what confuses me is what we should do when events  are in Y to X correspondondence. How should I design around that? (in example think to an enemy with an Health bar, when enemy dies we should get rid of bar and enemy sprite too, so we have 2 pieces of code that needs to be notified: the enemy sprite and the health bar).

**Comment by sebas77** [comment]
oh damn, I just noticed this question! Sorry for the super late answer.

the first case is normal, it's what usually happens. An object can implement different component interfaces and each component can be used by different engines through nodes.

for the second case. Everything must be managed by engines, even the GUI. In order to not mess with the code and keep well defined separation between components and engines, nodes are created. You will create a Node for the GUI and a Node for the Sprite. Both Nodes use the same component which dispatch an event when the enemies dies (from the EnemyEngine, and therefore through the EnemyNode).
